version: "3"

services:
  go-server:
    container_name: go-server
    build:
      context: .
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - type: bind
        source: /Users/younggyo/Documents/mount
        target: /exports
        