version: "3"

services:
  go-server:
    container_name: go-server
    build:
      context: .
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - nfs-server
  nfs-server:
    image: itsthenetwork/nfs-server-alpine:12
    container_name: nfs-server
    platform: linux/amd64
    ports:
      - "2049:2049"
    environment:
      - SHARED_DIRECTORY=/exports
      - PERMITTED=*
      - READ_ONLY=false
      - SYNC=async
    volumes:
      - type: bind
        source: /Users/younggyo/Documents/mount
        target: /exports
        